### ISSUE TITLE
Phi capitalisation

### ISSUE THREAD

**Issue by HajFunk** [Tobotis/fourier-guide#6]
In [Polarkoordinaten](https://fourier.tobotis.com/appendix/complex-numbers/1-complex-plane#polarkoordinaten) the Phi is capitalised in the task and is not capitalised in the graph.

**Comment by Tobotis** [comment]
It was because of the Symbol U+03C6, which is rendered differently in different browsers I guess (somtimes $\varphi$, somtimes $\phi$). Just replaced it with $\theta$ and U+03B8.
